spring:
  profiles:
    active: dev
  application:
    name: lzhphantom-@artifactId@
  config:
    import:
      - optional:nacos:lzhphantom-application-@profiles.active@.yaml
      - optional:nacos:${spring.application.name}-@profiles.active@.yaml
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
        file-extension: yaml
      username: @nacos.username@
      password: @nacos.password@
server:
  port: 80
