server:
    port: 4000
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/lzhphantom_exam?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=true
        username: root
        password: root
    main:
        allow-bean-definition-overriding: true
    profiles:
        active: dev
    config:
        import: optional:nacos:lzhphantom-user-dev.yml
    application:
        name: user
    cloud:
      nacos:
        discovery:
            server-addr: localhost:8848
            username: nacos
            password: nacos
        config:
            server-addr: localhost:8848
            file-extension: yaml
