server:
  port: 4000
spring:
  application:
    name: lzhphantom-user
  config:
    import:
      - optional:nacos:lzhphantom-application-@profiles.active@.yml
      - optional:nacos:${spring.application.name}-@profiles.active@.yml
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: @nacos.username@
        password: @nacos.password@
      config:
        server-addr: localhost:8848
        file-extension: yml